#!/bin/sh
# KHr from: https://openwrt.org/faq/how_to_get_a_list_of_connected_clients
#
# This script is located under /usr/bin/clients
#
# Shows MAC, IP address and any hostname info for all connected wifi devices
# written for openwrt 12.09 Attitude Adjustment

LOG="/var/log/clients.log"
LOG_MAX=500

info_log() {
  local text=$1
  local stamp="$(date)"
  echo "$stamp: $text" >> "$LOG"
}

# Limit log size
if [[ -f "$LOG" ]]; then
  while [[ $(wc -l < "$LOG") -gt $LOG_MAX ]]; do
    sed -i '1d' "$LOG"
  done
else
  touch "$LOG"
  info_log "System startup"
fi

echo    "Connected WIFI devices:"
echo -e "IP address  \tname     \tMAC address"
# list all wireless network interfaces
# (for universal driver; see wiki article for alternative commands)
for interface in `iwinfo | grep ESSID | cut -f 1 -s -d" "`
do
  # for each interface, get mac addresses of connected stations/clients
  maclist=`iwinfo $interface assoclist | grep dBm | cut -f 1 -s -d" "`
  # for each mac address in that list...
  for mac in $maclist
  do
    # If a DHCP lease has been given out by dnsmasq,
    # save it.
    ip=`cat /tmp/dhcp.leases | cut -f 2,3,4 -s -d" " | grep -i $mac | cut -f 2 -s -d" "`
    host=`cat /tmp/dhcp.leases | cut -f 2,3,4 -s -d" " | grep -i $mac | cut -f 3 -s -d" "`
    if [[ -z $host ]]; then
      host="     "
    fi
    # ... show the mac address:
    if [[ ! -z $ip ]]; then
      echo -e "$ip\t$host\t$mac"
      info_log "ip=$ip host=$host mac=$mac"
    fi
  done
done
