#!/bin/sh
# KHr
#
# Modem reset procedure with Gl.iNet GL-X750 firmware 4.0.
#

echo 0 > /sys/class/gpio/pci_power/value
sleep 5
echo 1 > /sys/class/gpio/pci_power/value
sleep 10
/etc/init.d/modem-init restart
